module.exports = {
  // 🔹 ESTOQUE COMPLETO
  stock: [
    // 89100221
    {
      productId: "89100221",
      batchId: null,
      center: "0001",
      deposit: "C050",
      qty: 10,
      isPlatform: "N",
    },
    {
      productId: "89100221",
      batchId: null,
      center: "0002",
      deposit: "C010",
      qty: 10,
      isPlatform: "N",
    },
    {
      productId: "89100221",
      batchId: null,
      center: "0002",
      deposit: "C050",
      qty: 5,
      isPlatform: "N",
    },
    {
      productId: "89100221",
      batchId: null,
      center: "0038",
      deposit: "C010",
      qty: 200,
      isPlatform: "N",
    },
    {
      productId: "89100221",
      batchId: null,
      center: "0019",
      deposit: "C010",
      qty: 1000,
      isPlatform: "N",
    },
    {
      productId: "89100221",
      batchId: null,
      center: "0019",
      deposit: "C050",
      qty: 300,
      isPlatform: "N",
    },

    // 89100222
    {
      productId: "89100222",
      batchId: null,
      center: "0001",
      deposit: "C050",
      qty: 200,
      isPlatform: "N",
    },
    {
      productId: "89100222",
      batchId: null,
      center: "0002",
      deposit: "C010",
      qty: 0,
      isPlatform: "N",
    },
    {
      productId: "89100222",
      batchId: null,
      center: "0002",
      deposit: "C050",
      qty: 0,
      isPlatform: "N",
    },
    {
      productId: "89100222",
      batchId: null,
      center: "0038",
      deposit: "C010",
      qty: 100,
      isPlatform: "N",
    },
    {
      productId: "89100222",
      batchId: null,
      center: "0019",
      deposit: "C010",
      qty: 4000,
      isPlatform: "N",
    },
    {
      productId: "89100222",
      batchId: null,
      center: "0019",
      deposit: "C050",
      qty: 500,
      isPlatform: "N",
    },

    // 89100223 (PLATAFORMA)
    {
      productId: "89100223",
      batchId: null,
      center: "0001",
      deposit: "C050",
      qty: 2,
      isPlatform: "N",
    },
    {
      productId: "89100223",
      batchId: null,
      center: "0002",
      deposit: "C010",
      qty: 0,
      isPlatform: "N",
    },
    {
      productId: "89100223",
      batchId: null,
      center: "0002",
      deposit: "C050",
      qty: 0,
      isPlatform: "N",
    },
    {
      productId: "89100223",
      batchId: null,
      center: "0038",
      deposit: "C010",
      qty: 0,
      isPlatform: "N",
    },
    {
      productId: "89100223",
      batchId: null,
      center: "0019",
      deposit: "C010",
      qty: 2,
      isPlatform: "N",
    },
    {
      productId: "89100223",
      batchId: null,
      center: "0019",
      deposit: "C050",
      qty: 1,
      isPlatform: "N",
    },
    {
      productId: "89100223",
      batchId: null,
      center: "0099",
      deposit: "C010",
      qty: 1000,
      isPlatform: "Y",
    },
    {
      productId: "89100223",
      batchId: null,
      center: "0519",
      deposit: "C010",
      qty: 200,
      isPlatform: "Y",
    },

    // 89100224 (COM LOTE)
    {
      productId: "89100224",
      batchId: "AAA",
      center: "0001",
      deposit: "C050",
      qty: 1000,
      isPlatform: "N",
    },
    {
      productId: "89100224",
      batchId: "BBB",
      center: "0002",
      deposit: "C010",
      qty: 10,
      isPlatform: "N",
    },
    {
      productId: "89100224",
      batchId: "CCC",
      center: "0002",
      deposit: "C050",
      qty: 5,
      isPlatform: "N",
    },
    {
      productId: "89100224",
      batchId: "AAA",
      center: "0038",
      deposit: "C010",
      qty: 200,
      isPlatform: "N",
    },
    {
      productId: "89100224",
      batchId: "BBB",
      center: "0019",
      deposit: "C010",
      qty: 1000,
      isPlatform: "N",
    },
    {
      productId: "89100224",
      batchId: "BBB",
      center: "0019",
      deposit: "C050",
      qty: 300,
      isPlatform: "N",
    },
  ],

  // 🔹 ESTRUTURA LOGÍSTICA COMPLETA
  logistics: [
    // ===== LOJA 0001 =====
    {
      salesOffice: "0001",
      stockCenter: "0001",
      stockDeposit: "C050",
      type: "LOJA",
      outCenter: "0001",
      outDeposit: "C050",
      flow: "CX",
      prepDays: 0,
      transfDays: 0,
    },
    {
      salesOffice: "0001",
      stockCenter: "0001",
      stockDeposit: "C060",
      type: "LOJA",
      outCenter: "0001",
      outDeposit: "C050",
      flow: "CX",
      prepDays: 0,
      transfDays: 0,
    },
    {
      salesOffice: "0001",
      stockCenter: "0001",
      stockDeposit: "C010",
      type: "LOJA",
      outCenter: "0001",
      outDeposit: "C010",
      flow: "REA",
      prepDays: 1,
      transfDays: 0,
    },
    {
      salesOffice: "0001",
      stockCenter: "0001",
      stockDeposit: "C050",
      type: "LOJA",
      outCenter: "0001",
      outDeposit: "C010",
      flow: "REA",
      prepDays: 1,
      transfDays: 0,
    },
    {
      salesOffice: "0001",
      stockCenter: "0099",
      stockDeposit: "C010",
      type: "CD/PLATAFORMA",
      outCenter: "0001",
      outDeposit: "C010",
      flow: "REA",
      prepDays: 1,
      transfDays: 1,
    },
    {
      salesOffice: "0001",
      stockCenter: "0001",
      stockDeposit: "C050",
      type: "LOJA",
      outCenter: "0001",
      outDeposit: "C010",
      flow: "ED",
      prepDays: 1,
      transfDays: 0,
    },
    {
      salesOffice: "0001",
      stockCenter: "0001",
      stockDeposit: "C010",
      type: "LOJA",
      outCenter: "0001",
      outDeposit: "C010",
      flow: "ED",
      prepDays: 1,
      transfDays: 0,
    },
    {
      salesOffice: "0001",
      stockCenter: "0001",
      stockDeposit: "C010",
      type: "LOJA",
      outCenter: "0001",
      outDeposit: "C010",
      flow: "ED",
      prepDays: 1,
      transfDays: 0,
    },
    {
      salesOffice: "0001",
      stockCenter: "0099",
      stockDeposit: "C010",
      type: "CD/PLATAFORMA",
      outCenter: "0099",
      outDeposit: "C010",
      flow: "ED",
      prepDays: 1,
      transfDays: 0,
    },
    {
      salesOffice: "0001",
      stockCenter: "0001",
      stockDeposit: "C050",
      type: "LOJA",
      outCenter: "0001",
      outDeposit: "C010",
      flow: "REI",
      prepDays: 1,
      transfDays: 0,
    },

    // ===== LOJA 0002 =====
    {
      salesOffice: "0002",
      stockCenter: "0002",
      stockDeposit: "C050",
      type: "LOJA",
      outCenter: "0002",
      outDeposit: "C050",
      flow: "CX",
      prepDays: 0,
      transfDays: 0,
    },
    {
      salesOffice: "0002",
      stockCenter: "0002",
      stockDeposit: "C060",
      type: "LOJA",
      outCenter: "0002",
      outDeposit: "C050",
      flow: "CX",
      prepDays: 0,
      transfDays: 0,
    },
    {
      salesOffice: "0002",
      stockCenter: "0002",
      stockDeposit: "C010",
      type: "LOJA",
      outCenter: "0002",
      outDeposit: "C010",
      flow: "REA",
      prepDays: 1,
      transfDays: 0,
    },
    {
      salesOffice: "0002",
      stockCenter: "0002",
      stockDeposit: "C050",
      type: "LOJA",
      outCenter: "0002",
      outDeposit: "C010",
      flow: "REA",
      prepDays: 1,
      transfDays: 0,
    },
    {
      salesOffice: "0002",
      stockCenter: "0099",
      stockDeposit: "C010",
      type: "CD/PLATAFORMA",
      outCenter: "0099",
      outDeposit: "C010",
      flow: "ED",
      prepDays: 1,
      transfDays: 0,
    },
    {
      salesOffice: "0002",
      stockCenter: "0002",
      stockDeposit: "C010",
      type: "LOJA",
      outCenter: "0002",
      outDeposit: "C010",
      flow: "ED",
      prepDays: 1,
      transfDays: 0,
    },
    {
      salesOffice: "0002",
      stockCenter: "0002",
      stockDeposit: "C050",
      type: "LOJA",
      outCenter: "0002",
      outDeposit: "C010",
      flow: "ED",
      prepDays: 1,
      transfDays: 0,
    },

    // ===== LOJA 0038 =====
    {
      salesOffice: "0038",
      stockCenter: "0038",
      stockDeposit: "C050",
      type: "LOJA",
      outCenter: "0038",
      outDeposit: "C050",
      flow: "CX",
      prepDays: 0,
      transfDays: 0,
    },
    {
      salesOffice: "0038",
      stockCenter: "0038",
      stockDeposit: "C060",
      type: "LOJA",
      outCenter: "0038",
      outDeposit: "C050",
      flow: "CX",
      prepDays: 0,
      transfDays: 0,
    },
    {
      salesOffice: "0038",
      stockCenter: "0038",
      stockDeposit: "C010",
      type: "LOJA",
      outCenter: "0038",
      outDeposit: "C010",
      flow: "REA",
      prepDays: 1,
      transfDays: 0,
    },
    {
      salesOffice: "0038",
      stockCenter: "0038",
      stockDeposit: "C050",
      type: "LOJA",
      outCenter: "0038",
      outDeposit: "C010",
      flow: "REA",
      prepDays: 1,
      transfDays: 0,
    },
    {
      salesOffice: "0038",
      stockCenter: "0038",
      stockDeposit: "C050",
      type: "LOJA",
      outCenter: "0038",
      outDeposit: "C010",
      flow: "ED",
      prepDays: 1,
      transfDays: 0,
    },
    {
      salesOffice: "0038",
      stockCenter: "0038",
      stockDeposit: "C010",
      type: "LOJA",
      outCenter: "0038",
      outDeposit: "C010",
      flow: "ED",
      prepDays: 1,
      transfDays: 0,
    },
    {
      salesOffice: "0038",
      stockCenter: "0038",
      stockDeposit: "C010",
      type: "LOJA",
      outCenter: "0038",
      outDeposit: "C010",
      flow: "ED",
      prepDays: 1,
      transfDays: 0,
    },
    {
      salesOffice: "0038",
      stockCenter: "0099",
      stockDeposit: "C010",
      type: "CD",
      outCenter: "0038",
      outDeposit: "C010",
      flow: "ED",
      prepDays: 1,
      transfDays: 10,
    },

    // ===== LOJA 0019 =====
    {
      salesOffice: "0019",
      stockCenter: "0019",
      stockDeposit: "C050",
      type: "LOJA",
      outCenter: "0019",
      outDeposit: "C050",
      flow: "CX",
      prepDays: 0,
      transfDays: 0,
    },
    {
      salesOffice: "0019",
      stockCenter: "0019",
      stockDeposit: "C060",
      type: "LOJA",
      outCenter: "0019",
      outDeposit: "C050",
      flow: "CX",
      prepDays: 0,
      transfDays: 0,
    },
    {
      salesOffice: "0019",
      stockCenter: "0019",
      stockDeposit: "C010",
      type: "LOJA",
      outCenter: "0019",
      outDeposit: "C010",
      flow: "REA",
      prepDays: 1,
      transfDays: 0,
    },
    {
      salesOffice: "0019",
      stockCenter: "0019",
      stockDeposit: "C050",
      type: "LOJA",
      outCenter: "0019",
      outDeposit: "C010",
      flow: "REA",
      prepDays: 1,
      transfDays: 0,
    },
    {
      salesOffice: "0019",
      stockCenter: "0019",
      stockDeposit: "C050",
      type: "LOJA",
      outCenter: "0019",
      outDeposit: "C010",
      flow: "ED",
      prepDays: 1,
      transfDays: 0,
    },
    {
      salesOffice: "0019",
      stockCenter: "0019",
      stockDeposit: "C010",
      type: "LOJA",
      outCenter: "0019",
      outDeposit: "C010",
      flow: "ED",
      prepDays: 1,
      transfDays: 0,
    },
    {
      salesOffice: "0019",
      stockCenter: "0019",
      stockDeposit: "C010",
      type: "LOJA",
      outCenter: "0019",
      outDeposit: "C010",
      flow: "ED",
      prepDays: 1,
      transfDays: 0,
    },
    {
      salesOffice: "0019",
      stockCenter: "0099",
      stockDeposit: "C010",
      type: "CD",
      outCenter: "0019",
      outDeposit: "C010",
      flow: "ED",
      prepDays: 1,
      transfDays: 8,
    },
    {
      salesOffice: "0019",
      stockCenter: "0519",
      stockDeposit: "C010",
      type: "PLATAFORMA",
      outCenter: "0519",
      outDeposit: "C010",
      flow: "ED",
      prepDays: 1,
      transfDays: 0,
    },
  ],
};
